version: '3.8'

services:
  client: 
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5173:5173" 

  server1: 
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "7000:7000"  
    depends_on:
      - mongo

  server2: 
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "7001:7000" 
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  mongo_data:
